baseURL = 'https://hamon.dev/'
title = 'hamon.dev'
languageCode = 'en'
defaultContentLanguage = 'en'
theme = 'hugo-coder'

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  author = "dominic hamon"
  info = "🏢 engineering manager .. 🔙 ex-physicist .. 🐕 rescuer .. 💀 tattooed troublemaker .. 🧠🌈"
  description = "dominic hamon's site"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"

  dateFormat = "2006-01-02"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2022

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  customCSS = []
  customSCSS = []
  customJS = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
  name = "github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/dominichamon/"
[[params.social]]
  name = "linkedin"
  icon = "fa fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/dominic-hamon-1733302/"
[[params.social]]
  name = "stackoverflow"
  icon = "fa fa-stack-overflow fa-2x"
  weight = 4
  url = "https://stackoverflow.com/users/55227/dma"
[[params.social]]
  name = "steam"
  icon = "fa fa-steam fa-2x"
  weight = 7
  url = "https://steamcommunity.com/profiles/76561197979265572/"
[[params.social]]
  name = "twitch"
  icon = "fa fa-twitch fa-2x"
  weight = 5
  url = "https://www.twitch.tv/dma42"
[[params.social]]
  name = "mastodon"
  icon = "fa fa-mastodon fa-2x"
  weight = 2
  url = "https://hachyderm.io/@dma"
#[[params.social]]
#  name = "discord"
#  icon = "fa fa-discord fa-2x"
#  weight = 3
# TODO
#  url = "https://twitter.com/runtime/"
[[params.social]]
  name = "twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 6
  url = "https://twitter.com/runtime/"
[[params.social]]
  name = "RSS"
  icon = "fa fa-2x fa-rss"
  weight = 4
  url = "https://hamon.dev/index.xml"
  rel = "alternate"
  type = "application/rss+xml"

# Menu links
[[menu.main]]
  name = "Projects"
  weight = 1
  url = "projects/"
[[menu.main]]
  name = "Blog"
  weight = 2
  url  = "blog/"
[[menu.main]]
  name = "About"
  weight = 3
  url = "https://dominichamon.com/"
